import type { ImageSourcePropType } from "react-native";

import type { FortuneCategory } from "../types/tarot";

export const backgroundImages = {
  lobby: require("../../assets/backgrounds/lobby.png") as ImageSourcePropType,
  cardSelect: require("../../assets/backgrounds/card-select.png") as ImageSourcePropType,
  result: require("../../assets/backgrounds/result.png") as ImageSourcePropType
};

export const tarotCardBackImage = require("../../assets/cards/back.png") as ImageSourcePropType;
export const tarotCardBackSelectedImage = require("../../assets/cards/back_selected.png") as ImageSourcePropType;

export const cardFrontImages: Record<string, ImageSourcePropType> = {
  the_fool: require("../../assets/cards/the_fool.png") as ImageSourcePropType,
  the_magician: require("../../assets/cards/the_magician.png") as ImageSourcePropType,
  the_high_priestess: require("../../assets/cards/the_high_priestess.png") as ImageSourcePropType,
  the_empress: require("../../assets/cards/the_empress.png") as ImageSourcePropType,
  the_emperor: require("../../assets/cards/the_emperor.png") as ImageSourcePropType,
  the_hierophant: require("../../assets/cards/the_hierophant.png") as ImageSourcePropType,
  the_lovers: require("../../assets/cards/the_lovers.png") as ImageSourcePropType,
  the_chariot: require("../../assets/cards/the_chariot.png") as ImageSourcePropType,
  strength: require("../../assets/cards/strength.png") as ImageSourcePropType,
  the_hermit: require("../../assets/cards/the_hermit.png") as ImageSourcePropType,
  wheel_of_fortune: require("../../assets/cards/wheel_of_fortune.png") as ImageSourcePropType,
  justice: require("../../assets/cards/justice.png") as ImageSourcePropType,
  the_hanged_man: require("../../assets/cards/the_hanged_man.png") as ImageSourcePropType,
  death: require("../../assets/cards/death.png") as ImageSourcePropType,
  temperance: require("../../assets/cards/temperance.png") as ImageSourcePropType,
  the_devil: require("../../assets/cards/the_devil.png") as ImageSourcePropType,
  the_tower: require("../../assets/cards/the_tower.png") as ImageSourcePropType,
  the_star: require("../../assets/cards/the_star.png") as ImageSourcePropType,
  the_moon: require("../../assets/cards/the_moon.png") as ImageSourcePropType,
  the_sun: require("../../assets/cards/the_sun.png") as ImageSourcePropType,
  judgement: require("../../assets/cards/judgement.png") as ImageSourcePropType,
  the_world: require("../../assets/cards/the_world.png") as ImageSourcePropType,
  ace_of_wands: require("../../assets/cards/ace_of_wands.png") as ImageSourcePropType,
  two_of_wands: require("../../assets/cards/two_of_wands.png") as ImageSourcePropType,
  three_of_wands: require("../../assets/cards/three_of_wands.png") as ImageSourcePropType,
  four_of_wands: require("../../assets/cards/four_of_wands.png") as ImageSourcePropType,
  five_of_wands: require("../../assets/cards/five_of_wands.png") as ImageSourcePropType,
  six_of_wands: require("../../assets/cards/six_of_wands.png") as ImageSourcePropType,
  seven_of_wands: require("../../assets/cards/seven_of_wands.png") as ImageSourcePropType,
  eight_of_wands: require("../../assets/cards/eight_of_wands.png") as ImageSourcePropType,
  nine_of_wands: require("../../assets/cards/nine_of_wands.png") as ImageSourcePropType,
  ten_of_wands: require("../../assets/cards/ten_of_wands.png") as ImageSourcePropType,
  page_of_wands: require("../../assets/cards/page_of_wands.png") as ImageSourcePropType,
  knight_of_wands: require("../../assets/cards/knight_of_wands.png") as ImageSourcePropType,
  queen_of_wands: require("../../assets/cards/queen_of_wands.png") as ImageSourcePropType,
  king_of_wands: require("../../assets/cards/king_of_wands.png") as ImageSourcePropType,
  ace_of_cups: require("../../assets/cards/ace_of_cups.png") as ImageSourcePropType,
  two_of_cups: require("../../assets/cards/two_of_cups.png") as ImageSourcePropType,
  three_of_cups: require("../../assets/cards/three_of_cups.png") as ImageSourcePropType,
  four_of_cups: require("../../assets/cards/four_of_cups.png") as ImageSourcePropType,
  five_of_cups: require("../../assets/cards/five_of_cups.png") as ImageSourcePropType,
  six_of_cups: require("../../assets/cards/six_of_cups.png") as ImageSourcePropType,
  seven_of_cups: require("../../assets/cards/seven_of_cups.png") as ImageSourcePropType,
  eight_of_cups: require("../../assets/cards/eight_of_cups.png") as ImageSourcePropType,
  nine_of_cups: require("../../assets/cards/nine_of_cups.png") as ImageSourcePropType,
  ten_of_cups: require("../../assets/cards/ten_of_cups.png") as ImageSourcePropType,
  page_of_cups: require("../../assets/cards/page_of_cups.png") as ImageSourcePropType,
  knight_of_cups: require("../../assets/cards/knight_of_cups.png") as ImageSourcePropType,
  queen_of_cups: require("../../assets/cards/queen_of_cups.png") as ImageSourcePropType,
  king_of_cups: require("../../assets/cards/king_of_cups.png") as ImageSourcePropType,
  ace_of_swords: require("../../assets/cards/ace_of_swords.png") as ImageSourcePropType,
  two_of_swords: require("../../assets/cards/two_of_swords.png") as ImageSourcePropType,
  three_of_swords: require("../../assets/cards/three_of_swords.png") as ImageSourcePropType,
  four_of_swords: require("../../assets/cards/four_of_swords.png") as ImageSourcePropType,
  five_of_swords: require("../../assets/cards/five_of_swords.png") as ImageSourcePropType,
  six_of_swords: require("../../assets/cards/six_of_swords.png") as ImageSourcePropType,
  seven_of_swords: require("../../assets/cards/seven_of_swords.png") as ImageSourcePropType,
  eight_of_swords: require("../../assets/cards/eight_of_swords.png") as ImageSourcePropType,
  nine_of_swords: require("../../assets/cards/nine_of_swords.png") as ImageSourcePropType,
  ten_of_swords: require("../../assets/cards/ten_of_swords.png") as ImageSourcePropType,
  page_of_swords: require("../../assets/cards/page_of_swords.png") as ImageSourcePropType,
  knight_of_swords: require("../../assets/cards/knight_of_swords.png") as ImageSourcePropType,
  queen_of_swords: require("../../assets/cards/queen_of_swords.png") as ImageSourcePropType,
  king_of_swords: require("../../assets/cards/king_of_swords.png") as ImageSourcePropType,
  ace_of_pentacles: require("../../assets/cards/ace_of_pentacles.png") as ImageSourcePropType,
  two_of_pentacles: require("../../assets/cards/two_of_pentacles.png") as ImageSourcePropType,
  three_of_pentacles: require("../../assets/cards/three_of_pentacles.png") as ImageSourcePropType,
  four_of_pentacles: require("../../assets/cards/four_of_pentacles.png") as ImageSourcePropType,
  five_of_pentacles: require("../../assets/cards/five_of_pentacles.png") as ImageSourcePropType,
  six_of_pentacles: require("../../assets/cards/six_of_pentacles.png") as ImageSourcePropType,
  seven_of_pentacles: require("../../assets/cards/seven_of_pentacles.png") as ImageSourcePropType,
  eight_of_pentacles: require("../../assets/cards/eight_of_pentacles.png") as ImageSourcePropType,
  nine_of_pentacles: require("../../assets/cards/nine_of_pentacles.png") as ImageSourcePropType,
  ten_of_pentacles: require("../../assets/cards/ten_of_pentacles.png") as ImageSourcePropType,
  page_of_pentacles: require("../../assets/cards/page_of_pentacles.png") as ImageSourcePropType,
  knight_of_pentacles: require("../../assets/cards/knight_of_pentacles.png") as ImageSourcePropType,
  queen_of_pentacles: require("../../assets/cards/queen_of_pentacles.png") as ImageSourcePropType,
  king_of_pentacles: require("../../assets/cards/king_of_pentacles.png") as ImageSourcePropType
};

export const categoryIconImages: Record<FortuneCategory, ImageSourcePropType> = {
  daily: require("../../assets/categories/daily.png") as ImageSourcePropType,
  love: require("../../assets/categories/love.png") as ImageSourcePropType,
  money: require("../../assets/categories/money.png") as ImageSourcePropType,
  work: require("../../assets/categories/work.png") as ImageSourcePropType,
  relationship: require("../../assets/categories/relationship.png") as ImageSourcePropType,
  choice: require("../../assets/categories/choice.png") as ImageSourcePropType,
  lotto: require("../../assets/categories/choice.png") as ImageSourcePropType
};
